# Site settings
title: "Blackguard"
description: "A Super Powereds Story"
# host: 0.0.0.0
# port: 3000
# url: "http://clever-wonder-3000.codio.io" 
url: "http://gaius.coffee"
baseurl: "/Blackguard"

# Build settings
markdown: kramdown
permalink: :categories/:title
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /Blackguard/about
  - title: "twt"
    url: http://twitter.com/GaiusCoffee
  - title: "git"
    url: http://github.com/GaiusCoffee
  - title: "rss"
    url: /Blackguard/feed.xml

gems:
  [jekyll-paginate]
